In [1]:
import pandas as pd
import geopandas as gpd
import re

from adat_strukturalas import *

In [2]:
gdf = gm_feldolgozas('../../adatok/fix/orszagos_teljes_ms.jsonl')

3686130 cím beolvasva
2190757 használható cím átadva ez a címek 59.43%-a
Google maps lekérdezés adatok standardizálva

In [3]:
gdf

,gid,utca,cim,telepules,iszam,orszag,geometry
0,47289911900891,Csalitos utca,6,Tököl,2316,Hungary,POINT (19.00889 47.28993)
1,47290591901043,Diana sétány,55,Tököl,2316,Hungary,POINT (19.01053 47.29057)
2,47289711900922,Diana sétány,71,Tököl,2316,Hungary,POINT (19.00921 47.28975)
3,47290281900996,Diana sétány,61,Tököl,2316,Hungary,POINT (19.00999 47.29026)
4,47283961900063,Diana sétány,147,Tököl,2316,Hungary,POINT (19.00071 47.28387)
...,...,...,...,...,...,...,...
2190752,46764301734911,Mogyorós utca,33,Balatongyörök,8313,Hungary,POINT (17.34902 46.76429)
2190753,46481191975105,Fő utca,181,Kiskunmajsa,6120,Hungary,POINT (19.75118 46.48119)
2190754,47452611956703,Bartók Béla utca,7,Tápiószecső,2251,Hungary,POINT (19.56709 47.4526)
2190755,47683021876780,Kálvária utca,52,Leányvár,2518,Hungary,POINT (18.76781 47.68296)
2190756,46171522060793,Petőfi Sándor utca,7,Magyarcsanád,6932,Hungary,POINT (20.60795 46.17151)

In [4]:
df = pd.read_parquet('../../adatok/fix/2014_2022_adatbazis_cimek_feldolgozott.parquet', engine='pyarrow')
df = df.drop_duplicates()

In [5]:
df

,szavazokorid,kozteruletid,kozteruletnevid,utca,cim,telepulesid,telepulesnev,telepulesnev_hu,eventfromid,date
0,228174,12752,449732,Demjéntelep,1,6,Sávoly,Sávoly,3611,2014-04-06
1,228174,12755,1330329,MÁV vasútállomás,1,6,Sávoly,Sávoly,3611,2014-04-06
2,228174,12755,1330329,MÁV vasútállomás,2,6,Sávoly,Sávoly,3611,2014-04-06
3,228174,12756,425713,Szabadság utca,29 B,6,Sávoly,Sávoly,3611,2014-04-06
4,228174,12756,425713,Szabadság utca,30 B,6,Sávoly,Sávoly,3611,2014-04-06
...,...,...,...,...,...,...,...,...,...,...
6524041,1610730,1346273,1489208,Mikszáth Kálmán utca,15,3063,Partiscum,Szeged,956243,2022-04-03
6524042,1610730,1346273,1489208,Mikszáth Kálmán utca,17,3063,Partiscum,Szeged,956243,2022-04-03
6524043,1610730,1346273,1489208,Mikszáth Kálmán utca,19,3063,Partiscum,Szeged,956243,2022-04-03
6524044,1610730,1346273,1489208,Mikszáth Kálmán utca,21,3063,Partiscum,Szeged,956243,2022-04-03
6524045,1610730,1346273,1489208,Mikszáth Kálmán utca,23,3063,Partiscum,Szeged,956243,2022-04-03

In [7]:
(2571424+135000+228000)/6500759 *100

45.13971368574039

In [4]:
df.query('telepulesnev == "Kovácsi"')

,szavazokorid,kozteruletid,kozteruletnevid,utca,cim,telepulesid,telepulesnev,telepulesnev_hu,eventfromid,date
185733,233377,14577,1330425,Gyulamajor major,1,2318,Kovácsi,Esztergom,3611,2014-04-06
185734,233377,14577,1330425,Gyulamajor major,2,2318,Kovácsi,Esztergom,3611,2014-04-06
185735,233377,14580,1330426,Jánosmajor major,1,2318,Kovácsi,Esztergom,3611,2014-04-06
185736,233377,14580,1330426,Jánosmajor major,4,2318,Kovácsi,Esztergom,3611,2014-04-06
185737,233377,1353666,1493602,Arany János utca,1,2318,Kovácsi,Esztergom,3611,2014-04-06
...,...,...,...,...,...,...,...,...,...,...
4146691,1603335,1457864,1596430,Jókai utca,5,2318,Kovácsi,Esztergom,956243,2022-04-03
4146692,1603335,1457864,1596430,Jókai utca,7,2318,Kovácsi,Esztergom,956243,2022-04-03
4146693,1603335,1457864,1596430,Jókai utca,9,2318,Kovácsi,Esztergom,956243,2022-04-03
4146694,1603335,1465279,1599946,Nyárfa üdülőpart,1,2318,Kovácsi,Esztergom,956243,2022-04-03
4146695,1603335,1465279,1599946,Nyárfa üdülőpart,2,2318,Kovácsi,Esztergom,956243,2022-04-03

In [7]:
df[~df['cim'].str.match(r'.*\d$', na=False)].query('utca == "Költő utca"').head(20)

,szavazokorid,kozteruletid,kozteruletnevid,utca,cim,telepulesid,telepulesnev,telepulesnev_hu,eventfromid,date
1840926,288995,1335170,1470302,Költő utca,2-4 A,2215,12. kerület,Budapest,3611,2014-04-06
1840930,288995,1335170,1470302,Költő utca,2-4 B,2215,12. kerület,Budapest,3611,2014-04-06
1840934,288995,1335170,1470302,Költő utca,2-4 C,2215,12. kerület,Budapest,3611,2014-04-06
1840938,288995,1335170,1470302,Költő utca,2-4 D,2215,12. kerület,Budapest,3611,2014-04-06
1840942,288995,1335170,1470302,Költő utca,2-4 C,2215,12. kerület,Budapest,3611,2014-04-06
1840946,288995,1335170,1470302,Költő utca,2-4 D,2215,12. kerület,Budapest,3611,2014-04-06
1840950,288995,1335170,1470302,Költő utca,2 A,2215,12. kerület,Budapest,3611,2014-04-06
1840954,288995,1335170,1470302,Költő utca,2 C,2215,12. kerület,Budapest,3611,2014-04-06
1840958,288995,1335170,1470302,Költő utca,4 A,2215,12. kerület,Budapest,3611,2014-04-06
1840962,288995,1335170,1470302,Költő utca,4 B,2215,12. kerület,Budapest,3611,2014-04-06
1840966,288995,1335170,1470302,Költő utca,4 C,2215,12. kerület,Budapest,3611,2014-04-06
1840970,288995,1335170,1470302,Költő utca,4 D,2215,12. kerület,Budapest,3611,2014-04-06
1840974,288995,1335170,1470302,Költő utca,18 A,2215,12. kerület,Budapest,3611,2014-04-06
1840978,288995,1335170,1470302,Költő utca,18 B,2215,12. kerület,Budapest,3611,2014-04-06
1840994,288995,1335170,1470302,Költő utca,18 A,2215,12. kerület,Budapest,3611,2014-04-06
1840998,288995,1335170,1470302,Költő utca,18 B,2215,12. kerület,Budapest,3611,2014-04-06
1841006,288995,1335170,1470302,Költő utca,2 A,2215,12. kerület,Budapest,3611,2014-04-06
1841010,288995,1335170,1470302,Költő utca,2 C,2215,12. kerület,Budapest,3611,2014-04-06
1841030,288995,1335170,1470302,Költő utca,8 B,2215,12. kerület,Budapest,3611,2014-04-06
1865783,289028,1335170,1470302,Költő utca,7 B,2215,12. kerület,Budapest,3611,2014-04-06

In [10]:
gdf[~gdf['cim'].str.match(r'.*\d$', na=False)].query('utca == "Költő utca"').head(20)

,gid,utca,cim,telepules,iszam,orszag,geometry
37368,47493951899457,Költő utca,35 C,Budapest,1121,Hungary,POINT (18.99457 47.49396)
116701,47500921898824,Költő utca,1 A,Budapest,1121,Hungary,POINT (18.98822 47.5009)
290609,47495141899529,Költő utca,26 D,Budapest,1121,Hungary,POINT (18.99538 47.49517)
438900,47494421899425,Költő utca,35 A,Budapest,1121,Hungary,POINT (18.99429 47.49435)
658754,47497561899396,Költő utca,23 A,Budapest,1121,Hungary,POINT (18.994 47.4976)
798914,47497831899468,Költő utca,22 A,Budapest,1121,Hungary,POINT (18.99471 47.49778)
982756,47504561990854,Költő utca,5 A,Jászberény,5100,Hungary,POINT (19.9084 47.50457)
1062966,47492701899606,Költő utca,42 C,Budapest,1121,Hungary,POINT (18.99606 47.49273)
1552952,47494851899365,Költő utca,33 B,Budapest,1121,Hungary,POINT (18.99364 47.49484)

In [6]:
gdf2 = gdf.rename(columns={"utca": "utca_gdf", "cim": "cim_gdf"})

merged = df.merge(
    gdf2,
    how="left",
    left_on=["utca", "cim", "telepulesnev_hu"],
    right_on=["utca_gdf", "cim_gdf", "telepules"],
    suffixes=("_df", "_gdf")
)

matched = merged[merged["geometry"].notna()]
unmatched = merged[merged["geometry"].isna()]

# none sorok kidobása
unmatched = unmatched.drop(columns=["gid", "utca_gdf", "cim_gdf", "telepules", 'iszam', 'orszag', "geometry"])

In [7]:
matched

,szavazokorid,kozteruletid,kozteruletnevid,utca,cim,telepulesid,telepulesnev,telepulesnev_hu,eventfromid,date,gid,utca_gdf,cim_gdf,telepules,iszam,orszag,geometry
8,228174,12756,425713,Szabadság utca,10,6,Sávoly,Sávoly,3611,2014-04-06,4.660009e+13,Szabadság utca,10,Sávoly,8732.0,Hungary,POINT (17.2619 46.60008)
9,228174,12756,425713,Szabadság utca,11,6,Sávoly,Sávoly,3611,2014-04-06,4.659982e+13,Szabadság utca,11,Sávoly,8732.0,Hungary,POINT (17.26066 46.59999)
10,228174,12756,425713,Szabadság utca,11,6,Sávoly,Sávoly,3611,2014-04-06,4.659999e+13,Szabadság utca,11,Sávoly,8732.0,Hungary,POINT (17.26066 46.59999)
11,228174,12756,425713,Szabadság utca,12,6,Sávoly,Sávoly,3611,2014-04-06,4.659999e+13,Szabadság utca,12,Sávoly,8732.0,Hungary,POINT (17.2604 46.59998)
12,228174,12756,425713,Szabadság utca,12,6,Sávoly,Sávoly,3611,2014-04-06,4.659979e+13,Szabadság utca,12,Sávoly,8732.0,Hungary,POINT (17.2604 46.59998)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7113853,1610730,1339972,1482900,Bartók tér,2,3063,Partiscum,Szeged,956243,2022-04-03,4.625506e+13,Bartók tér,2,Szeged,6722.0,Hungary,POINT (20.14414 46.25508)
7113868,1610730,1341379,1484310,Mérey utca,15 A,3063,Partiscum,Szeged,956243,2022-04-03,4.625717e+13,Mérey utca,15 A,Szeged,6722.0,Hungary,POINT (20.14335 46.25715)
7113878,1610730,1341379,1484310,Mérey utca,12,3063,Partiscum,Szeged,956243,2022-04-03,4.625609e+13,Mérey utca,12,Szeged,6722.0,Hungary,POINT (20.1446 46.25606)
7113912,1610730,1342204,1485135,Török utca,4,3063,Partiscum,Szeged,956243,2022-04-03,4.625607e+13,Török utca,4,Szeged,6722.0,Hungary,POINT (20.14402 46.25614)
7113930,1610730,1346273,1489208,Mikszáth Kálmán utca,11,3063,Partiscum,Szeged,956243,2022-04-03,4.625591e+13,Mikszáth Kálmán utca,11,Szeged,6722.0,Hungary,POINT (20.14305 46.25583)

In [8]:
unmatched

,szavazokorid,kozteruletid,kozteruletnevid,utca,cim,telepulesid,telepulesnev,telepulesnev_hu,eventfromid,date
0,228174,12752,449732,Demjéntelep,1,6,Sávoly,Sávoly,3611,2014-04-06
1,228174,12755,1330329,MÁV vasútállomás,1,6,Sávoly,Sávoly,3611,2014-04-06
2,228174,12755,1330329,MÁV vasútállomás,2,6,Sávoly,Sávoly,3611,2014-04-06
3,228174,12756,425713,Szabadság utca,29 B,6,Sávoly,Sávoly,3611,2014-04-06
4,228174,12756,425713,Szabadság utca,30 B,6,Sávoly,Sávoly,3611,2014-04-06
...,...,...,...,...,...,...,...,...,...,...
7113934,1610730,1346273,1489208,Mikszáth Kálmán utca,15,3063,Partiscum,Szeged,956243,2022-04-03
7113935,1610730,1346273,1489208,Mikszáth Kálmán utca,17,3063,Partiscum,Szeged,956243,2022-04-03
7113936,1610730,1346273,1489208,Mikszáth Kálmán utca,19,3063,Partiscum,Szeged,956243,2022-04-03
7113937,1610730,1346273,1489208,Mikszáth Kálmán utca,21,3063,Partiscum,Szeged,956243,2022-04-03
7113938,1610730,1346273,1489208,Mikszáth Kálmán utca,23,3063,Partiscum,Szeged,956243,2022-04-03

In [9]:
matched.query('date == "2022-04-03" & telepulesnev_hu == "Tököl"')

,szavazokorid,kozteruletid,kozteruletnevid,utca,cim,telepulesid,telepulesnev,telepulesnev_hu,eventfromid,date,gid,utca_gdf,cim_gdf,telepules,iszam,orszag,geometry
3639368,1600934,1362031,1501876,Duna utca,1,2717,Teckel,Tököl,956243,2022-04-03,4.733901e+13,Duna utca,1,Tököl,2316.0,Hungary,POINT (18.96849 47.33904)
3639378,1600934,1362031,1501876,Duna utca,12,2717,Teckel,Tököl,956243,2022-04-03,4.734088e+13,Duna utca,12,Tököl,2316.0,Hungary,POINT (18.96414 47.34087)
3639392,1600934,1362031,1501876,Duna utca,3,2717,Teckel,Tököl,956243,2022-04-03,4.733945e+13,Duna utca,3,Tököl,2316.0,Hungary,POINT (18.96725 47.33944)
3639395,1600934,1362031,1501876,Duna utca,4,2717,Teckel,Tököl,956243,2022-04-03,4.733891e+13,Duna utca,4,Tököl,2316.0,Hungary,POINT (18.96763 47.33894)
3639400,1600934,1362031,1501876,Duna utca,5,2717,Teckel,Tököl,956243,2022-04-03,4.733993e+13,Duna utca,5,Tököl,2316.0,Hungary,POINT (18.96596 47.33981)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5893371,1606585,1444320,1583040,Deák Ferenc utca,5,2717,Teckel,Tököl,956243,2022-04-03,4.730853e+13,Deák Ferenc utca,5,Tököl,2316.0,Hungary,POINT (18.97552 47.30848)
5893372,1606585,1444320,1583040,Deák Ferenc utca,6,2717,Teckel,Tököl,956243,2022-04-03,4.730821e+13,Deák Ferenc utca,6,Tököl,2316.0,Hungary,POINT (18.97573 47.30823)
5893373,1606585,1444320,1583040,Deák Ferenc utca,7,2717,Teckel,Tököl,956243,2022-04-03,4.730840e+13,Deák Ferenc utca,7,Tököl,2316.0,Hungary,POINT (18.97534 47.30841)
5893374,1606585,1444320,1583040,Deák Ferenc utca,8,2717,Teckel,Tököl,956243,2022-04-03,4.730805e+13,Deák Ferenc utca,8,Tököl,2316.0,Hungary,POINT (18.97552 47.30804)
5893375,1606585,1444320,1583040,Deák Ferenc utca,9,2717,Teckel,Tököl,956243,2022-04-03,4.730832e+13,Deák Ferenc utca,9,Tököl,2316.0,Hungary,POINT (18.97512 47.30832)

In [10]:
# 2. szabály

_ADDR = re.compile(r"^\s*(\d+)\s*(?:-\s*(\d+))?\s*([A-Za-z])?\s*$")

def parse_addr(s):
    '''
    szétszedi a cím bemenetet három tagra 12-14 C -> (12, 14, 'C')
    ha nem tudja megcsinálni akkor None
    '''
    
    if s is None or (isinstance(s, float) and pd.isna(s)):
        return None
        
    m = _ADDR.match(str(s))
    
    if not m:
        return None
        
    a = int(m.group(1))
    b = int(m.group(2)) if m.group(2) else a
    lo, hi = (a, b) if a <= b else (b, a)
    letter = m.group(3).upper() if m.group(3) else None
    
    return (lo, hi, letter)


def overlap(a, b):
    if a[2] is not None or b[2] is not None:
        if a[2] != b[2]:
            return False
    return max(a[0], b[0]) <= min(a[1], b[1])


def attach_by_range(df_unmatched, gdf, df_id_col="_df_rowid"):
    d = df_unmatched.copy()
    g = gdf.copy()

    if df_id_col not in d.columns:
        d[df_id_col] = range(len(d))

    # df-ből dobd a korábbról beragadt gdf-es oszlopokat
    d = d.drop(columns=[c for c in d.columns if "_gdf" in c], errors="ignore")
    # df oldali üres geometry ne zavarjon be
    d = d.drop(columns=["geometry"], errors="ignore")

    # cím parse: kizárjuk a visszafelé tartományt (b <= a)
    def _parse(s):
        if s is None or (isinstance(s, float) and pd.isna(s)):
            return None
        m = _ADDR.match(str(s))
        if not m:
            return None
        a = int(m.group(1))
        b_raw = m.group(2)
        if b_raw is not None:
            b = int(b_raw)
            if b <= a:         # <-- ez az új szabály
                return None
        else:
            b = a
        L = m.group(3).upper() if m.group(3) else None
        return (a, b, L)

    d["_a"] = d["cim"].map(_parse)
    g["_b"] = g["cim"].map(_parse)

    d = d[d["_a"].notna()]
    g = g[g["_b"].notna()]

    if d.empty or g.empty:
        empty = gpd.GeoDataFrame(d.iloc[0:0].copy(), geometry=None, crs=gdf.crs)
        still = d.drop(columns=["_a", df_id_col], errors="ignore")
        return empty, still

    d[["d_lo", "d_hi", "d_L"]] = pd.DataFrame(d["_a"].tolist(), index=d.index)
    g[["g_lo", "g_hi", "g_L"]] = pd.DataFrame(g["_b"].tolist(), index=g.index)

    # gdf kulcsok átnevezése, hogy megmaradjon minden
    g = g.rename(columns={"utca": "utca_gdf", "cim": "cim_gdf"})

    cand = d.merge(
        g,
        how="left",
        left_on=["utca", "telepulesnev"],
        right_on=["utca_gdf", "telepules"],
        suffixes=("_df", "_gdf"),
    )

    # numerikus átfedés
    num_ok = cand[["d_lo", "g_lo"]].max(axis=1) <= cand[["d_hi", "g_hi"]].min(axis=1)

    # betű szabály: ha bármelyiken van betű, egyezzen
    letter_needed = cand["d_L"].notna() | cand["g_L"].notna()
    letter_ok = ~letter_needed | (cand["d_L"] == cand["g_L"])

    m = num_ok & letter_ok & cand["g_lo"].notna()

    matched_df = cand[m].drop(
        columns=["_a", "_b", "d_lo", "d_hi", "d_L", "g_lo", "g_hi", "g_L"],
        errors="ignore",
    )

    # geometry oszlop kiválasztása (gdf-ből jövő)
    if "geometry_gdf" in matched_df.columns:
        geom_col = "geometry_gdf"
    elif "geometry" in matched_df.columns:
        geom_col = "geometry"
    else:
        geom_col = next((c for c in matched_df.columns if c.startswith("geometry") and "_gdf" in c), None)

    matched = gpd.GeoDataFrame(matched_df, geometry=geom_col, crs=gdf.crs) if geom_col else gpd.GeoDataFrame(matched_df, geometry=None, crs=gdf.crs)

    matched_ids = matched[df_id_col].unique()
    still_unmatched = d[~d[df_id_col].isin(matched_ids)].drop(
        columns=["_a", "d_lo", "d_hi", "d_L"],
        errors="ignore",
    )

    # kimenet takarítás: technikai oszlopok ki
    cleanup = [df_id_col]
    matched = matched.drop(columns=cleanup, errors="ignore")
    still_unmatched = still_unmatched.drop(columns=cleanup, errors="ignore")

    return matched, still_unmatched

In [11]:
matched2, unmatched2 = attach_by_range(unmatched, gdf)

In [12]:
matched2

,szavazokorid,kozteruletid,kozteruletnevid,utca,cim,telepulesid,telepulesnev,telepulesnev_hu,eventfromid,date,gid,utca_gdf,cim_gdf,telepules,iszam,orszag,geometry
5818,228182,1406442,1545628,Fő utca,27,8,Dunaremete,Dunaremete,3611,2014-04-06,4.787791e+13,Fő utca,27-47,Dunaremete,9235.0,Hungary,POINT (17.43452 47.87749)
5868,228182,1406442,1545628,Fő utca,30,8,Dunaremete,Dunaremete,3611,2014-04-06,4.787791e+13,Fő utca,27-47,Dunaremete,9235.0,Hungary,POINT (17.43452 47.87749)
5918,228182,1406442,1545628,Fő utca,31,8,Dunaremete,Dunaremete,3611,2014-04-06,4.787791e+13,Fő utca,27-47,Dunaremete,9235.0,Hungary,POINT (17.43452 47.87749)
5968,228182,1406442,1545628,Fő utca,34,8,Dunaremete,Dunaremete,3611,2014-04-06,4.787791e+13,Fő utca,27-47,Dunaremete,9235.0,Hungary,POINT (17.43452 47.87749)
6018,228182,1406442,1545628,Fő utca,45,8,Dunaremete,Dunaremete,3611,2014-04-06,4.787791e+13,Fő utca,27-47,Dunaremete,9235.0,Hungary,POINT (17.43452 47.87749)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69589592,1610615,1366558,1506351,Budai Nagy Antal utca,19,1213,Szentes,Szentes,956243,2022-04-03,4.664863e+13,Budai Nagy Antal utca,15-21,Szentes,6600.0,Hungary,POINT (20.26397 46.64898)
69590347,1610615,1419284,1558303,Csillag utca,2,1213,Szentes,Szentes,956243,2022-04-03,4.664626e+13,Csillag utca,2-4,Szentes,6600.0,Hungary,POINT (20.26571 46.64611)
69590352,1610615,1419284,1558303,Csillag utca,3,1213,Szentes,Szentes,956243,2022-04-03,4.664626e+13,Csillag utca,2-4,Szentes,6600.0,Hungary,POINT (20.26571 46.64611)
69611925,1610621,1429853,1568741,Ipartelepi út,32-36,1213,Szentes,Szentes,956243,2022-04-03,4.663590e+13,Ipartelepi út,32,Szentes,6600.0,Hungary,POINT (20.2782 46.63593)
69611929,1610621,1429853,1568741,Ipartelepi út,32-36,1213,Szentes,Szentes,956243,2022-04-03,4.663668e+13,Ipartelepi út,35,Szentes,6600.0,Hungary,POINT (20.27736 46.63667)

In [13]:
unmatched2

,szavazokorid,kozteruletid,kozteruletnevid,utca,cim,telepulesid,telepulesnev,telepulesnev_hu,eventfromid,date
0,228174,12752,449732,Demjéntelep,1,6,Sávoly,Sávoly,3611,2014-04-06
1,228174,12755,1330329,MÁV vasútállomás,1,6,Sávoly,Sávoly,3611,2014-04-06
2,228174,12755,1330329,MÁV vasútállomás,2,6,Sávoly,Sávoly,3611,2014-04-06
3,228174,12756,425713,Szabadság utca,29 B,6,Sávoly,Sávoly,3611,2014-04-06
4,228174,12756,425713,Szabadság utca,30 B,6,Sávoly,Sávoly,3611,2014-04-06
...,...,...,...,...,...,...,...,...,...,...
7113934,1610730,1346273,1489208,Mikszáth Kálmán utca,15,3063,Partiscum,Szeged,956243,2022-04-03
7113935,1610730,1346273,1489208,Mikszáth Kálmán utca,17,3063,Partiscum,Szeged,956243,2022-04-03
7113936,1610730,1346273,1489208,Mikszáth Kálmán utca,19,3063,Partiscum,Szeged,956243,2022-04-03
7113937,1610730,1346273,1489208,Mikszáth Kálmán utca,21,3063,Partiscum,Szeged,956243,2022-04-03
7113938,1610730,1346273,1489208,Mikszáth Kálmán utca,23,3063,Partiscum,Szeged,956243,2022-04-03

In [14]:
def attach_ignore_letter(df_unmatched, gdf, df_id_col="_df_rowid"):
    d = df_unmatched.copy()
    g = gdf.copy()

    if df_id_col not in d.columns:
        d[df_id_col] = range(len(d))

    # ha beragadt gdf-es oszlopok vannak a df_unmatched-ben, dobd ki
    d = d.drop(columns=[c for c in d.columns if "_gdf" in c], errors="ignore")
    d = d.drop(columns=["geometry"], errors="ignore")

    # csak szám/tartomány kell, betűt ignoráljuk
    # regex: 1) lo  2) hi(optional)  3) letter(optional)
    ext_d = d["cim"].astype("string").str.extract(_ADDR)
    ext_g = g["cim"].astype("string").str.extract(_ADDR)

    # lo/hi számokká
    d_lo = pd.to_numeric(ext_d[0], errors="coerce")
    d_hi = pd.to_numeric(ext_d[1], errors="coerce")
    g_lo = pd.to_numeric(ext_g[0], errors="coerce")
    g_hi = pd.to_numeric(ext_g[1], errors="coerce")

    # ha nincs hi, akkor hi=lo (pont)
    d_hi = d_hi.fillna(d_lo)
    g_hi = g_hi.fillna(g_lo)

    # kizárjuk a visszafelé tartományt: ahol volt hi és hi <= lo
    d_has_hi = ext_d[1].notna()
    g_has_hi = ext_g[1].notna()
    d_ok = d_lo.notna() & d_hi.notna() & (~d_has_hi | (d_hi > d_lo))
    g_ok = g_lo.notna() & g_hi.notna() & (~g_has_hi | (g_hi > g_lo))

    d = d[d_ok].copy()
    g = g[g_ok].copy()

    if d.empty or g.empty:
        empty = gpd.GeoDataFrame(d.iloc[0:0].copy(), geometry=None, crs=gdf.crs)
        still = d.drop(columns=[df_id_col], errors="ignore")
        return empty, still

    # a szűrt indexek alapján töltsük vissza a lo/hi-t
    d["d_lo"] = d_lo.loc[d.index].astype(int)
    d["d_hi"] = d_hi.loc[d.index].astype(int)
    g["g_lo"] = g_lo.loc[g.index].astype(int)
    g["g_hi"] = g_hi.loc[g.index].astype(int)

    # gdf kulcsok átnevezése, hogy minden megmaradjon
    g = g.rename(columns={"utca": "utca_gdf", "cim": "cim_gdf"})

    cand = d.merge(
        g,
        how="left",
        left_on=["utca", "telepulesnev"],
        right_on=["utca_gdf", "telepules"],
        suffixes=("_df", "_gdf"),
    )

    # numerikus átfedés
    num_ok = cand[["d_lo", "g_lo"]].max(axis=1) <= cand[["d_hi", "g_hi"]].min(axis=1)
    m = num_ok & cand["g_lo"].notna()

    matched_df = cand[m].drop(columns=["d_lo", "d_hi", "g_lo", "g_hi"], errors="ignore")

    # geometry oszlop (gdf-ből jövő)
    if "geometry_gdf" in matched_df.columns:
        geom_col = "geometry_gdf"
    elif "geometry" in matched_df.columns:
        geom_col = "geometry"
    else:
        geom_col = next((c for c in matched_df.columns if c.startswith("geometry") and "_gdf" in c), None)

    matched = gpd.GeoDataFrame(matched_df, geometry=geom_col, crs=gdf.crs) if geom_col else gpd.GeoDataFrame(matched_df, geometry=None, crs=gdf.crs)

    matched_ids = matched[df_id_col].unique()
    still_unmatched = d[~d[df_id_col].isin(matched_ids)].drop(columns=["d_lo", "d_hi"], errors="ignore")

    # technikai oszlop kidobása a kimenetből
    matched = matched.drop(columns=[df_id_col], errors="ignore")
    still_unmatched = still_unmatched.drop(columns=[df_id_col], errors="ignore")

    return matched, still_unmatched

In [15]:
matched3, unmatched3 = attach_ignore_letter(unmatched2, gdf)

In [16]:
matched3

,szavazokorid,kozteruletid,kozteruletnevid,utca,cim,telepulesid,telepulesnev,telepulesnev_hu,eventfromid,date,gid,utca_gdf,cim_gdf,telepules,iszam,orszag,geometry
138,228174,12756,425713,Szabadság utca,31 A,6,Sávoly,Sávoly,3611,2014-04-06,4.660032e+13,Szabadság utca,31,Sávoly,8732.0,Hungary,POINT (17.26027 46.60032)
175,228174,12756,425713,Szabadság utca,31 B,6,Sávoly,Sávoly,3611,2014-04-06,4.660032e+13,Szabadság utca,31,Sávoly,8732.0,Hungary,POINT (17.26027 46.60032)
731,228174,1396834,1536151,Kossuth utca,10 A,6,Sávoly,Sávoly,3611,2014-04-06,4.658865e+13,Kossuth utca,10,Sávoly,8732.0,Hungary,POINT (17.26902 46.58864)
816,228174,1396834,1536151,Kossuth utca,34 C,6,Sávoly,Sávoly,3611,2014-04-06,4.658454e+13,Kossuth utca,34,Sávoly,8732.0,Hungary,POINT (17.2698 46.58456)
868,228174,1396834,1536151,Kossuth utca,34 D,6,Sávoly,Sávoly,3611,2014-04-06,4.658454e+13,Kossuth utca,34,Sávoly,8732.0,Hungary,POINT (17.2698 46.58456)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65894570,1610621,1409778,1548953,Horváth telep,2 A,1213,Szentes,Szentes,956243,2022-04-03,4.663998e+13,Horváth telep,2,Szentes,6600.0,Hungary,POINT (20.27563 46.63999)
65894579,1610621,1409778,1548953,Horváth telep,9 A,1213,Szentes,Szentes,956243,2022-04-03,4.663910e+13,Horváth telep,9,Szentes,6600.0,Hungary,POINT (20.27578 46.63916)
65894615,1610621,1413865,1552982,Nádasdy utca,12 A,1213,Szentes,Szentes,956243,2022-04-03,4.663514e+13,Nádasdy utca,12,Szentes,6600.0,Hungary,POINT (20.27404 46.63522)
65894638,1610621,1413865,1552982,Nádasdy utca,19 A,1213,Szentes,Szentes,956243,2022-04-03,4.663474e+13,Nádasdy utca,19,Szentes,6600.0,Hungary,POINT (20.27455 46.63485)
65894640,1610621,1413865,1552982,Nádasdy utca,19 A,1213,Szentes,Szentes,956243,2022-04-03,4.663484e+13,Nádasdy utca,19,Szentes,6600.0,Hungary,POINT (20.27455 46.63485)

In [17]:
unmatched3

,szavazokorid,kozteruletid,kozteruletnevid,utca,cim,telepulesid,telepulesnev,telepulesnev_hu,eventfromid,date
0,228174,12752,449732,Demjéntelep,1,6,Sávoly,Sávoly,3611,2014-04-06
1,228174,12755,1330329,MÁV vasútállomás,1,6,Sávoly,Sávoly,3611,2014-04-06
2,228174,12755,1330329,MÁV vasútállomás,2,6,Sávoly,Sávoly,3611,2014-04-06
3,228174,12756,425713,Szabadság utca,29 B,6,Sávoly,Sávoly,3611,2014-04-06
4,228174,12756,425713,Szabadság utca,30 B,6,Sávoly,Sávoly,3611,2014-04-06
...,...,...,...,...,...,...,...,...,...,...
7113934,1610730,1346273,1489208,Mikszáth Kálmán utca,15,3063,Partiscum,Szeged,956243,2022-04-03
7113935,1610730,1346273,1489208,Mikszáth Kálmán utca,17,3063,Partiscum,Szeged,956243,2022-04-03
7113936,1610730,1346273,1489208,Mikszáth Kálmán utca,19,3063,Partiscum,Szeged,956243,2022-04-03
7113937,1610730,1346273,1489208,Mikszáth Kálmán utca,21,3063,Partiscum,Szeged,956243,2022-04-03
7113938,1610730,1346273,1489208,Mikszáth Kálmán utca,23,3063,Partiscum,Szeged,956243,2022-04-03

In [18]:
matched3.query('telepulesnev_hu == "Tököl"')

Empty GeoDataFrame
Columns: [szavazokorid, kozteruletid, kozteruletnevid, utca, cim, telepulesid, telepulesnev, telepulesnev_hu, eventfromid, date, gid, utca_gdf, cim_gdf, telepules, iszam, orszag, geometry]
Index: []

In [19]:
unmatched3.query('date == "2022-04-03"').size

15628240

In [20]:
unmatched3.query('telepulesnev_hu == "Tököl"')

,szavazokorid,kozteruletid,kozteruletnevid,utca,cim,telepulesid,telepulesnev,telepulesnev_hu,eventfromid,date
2777318,294736,1362031,1501876,Duna utca,10 A,2717,Teckel,Tököl,3611,2014-04-06
2777327,294736,1362031,1501876,Duna utca,12 C,2717,Teckel,Tököl,3611,2014-04-06
2777328,294736,1362031,1501876,Duna utca,14 A,2717,Teckel,Tököl,3611,2014-04-06
2777337,294736,1362031,1501876,Duna utca,10,2717,Teckel,Tököl,3611,2014-04-06
2777348,294736,1362031,1501876,Duna utca,14,2717,Teckel,Tököl,3611,2014-04-06
...,...,...,...,...,...,...,...,...,...,...
5893359,1606585,1443984,1582703,Búzavirág utca,9,2717,Teckel,Tököl,956243,2022-04-03
5893363,1606585,1444320,1583040,Deák Ferenc utca,12,2717,Teckel,Tököl,956243,2022-04-03
5893364,1606585,1444320,1583040,Deák Ferenc utca,13,2717,Teckel,Tököl,956243,2022-04-03
5893376,1606585,1457402,1595980,Szent Gellért utca,1,2717,Teckel,Tököl,956243,2022-04-03
5893377,1606585,1457402,1595980,Szent Gellért utca,3,2717,Teckel,Tököl,956243,2022-04-03

In [21]:
all_matched = pd.concat([matched, matched2, matched3], ignore_index=True)
all_matched = gpd.GeoDataFrame(all_matched, geometry="geometry", crs=gdf.crs)

In [22]:
all_matched

,szavazokorid,kozteruletid,kozteruletnevid,utca,cim,telepulesid,telepulesnev,telepulesnev_hu,eventfromid,date,gid,utca_gdf,cim_gdf,telepules,iszam,orszag,geometry
0,228174,12756,425713,Szabadság utca,10,6,Sávoly,Sávoly,3611,2014-04-06,4.660009e+13,Szabadság utca,10,Sávoly,8732.0,Hungary,POINT (17.2619 46.60008)
1,228174,12756,425713,Szabadság utca,11,6,Sávoly,Sávoly,3611,2014-04-06,4.659982e+13,Szabadság utca,11,Sávoly,8732.0,Hungary,POINT (17.26066 46.59999)
2,228174,12756,425713,Szabadság utca,11,6,Sávoly,Sávoly,3611,2014-04-06,4.659999e+13,Szabadság utca,11,Sávoly,8732.0,Hungary,POINT (17.26066 46.59999)
3,228174,12756,425713,Szabadság utca,12,6,Sávoly,Sávoly,3611,2014-04-06,4.659999e+13,Szabadság utca,12,Sávoly,8732.0,Hungary,POINT (17.2604 46.59998)
4,228174,12756,425713,Szabadság utca,12,6,Sávoly,Sávoly,3611,2014-04-06,4.659979e+13,Szabadság utca,12,Sávoly,8732.0,Hungary,POINT (17.2604 46.59998)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3954623,1610621,1409778,1548953,Horváth telep,2 A,1213,Szentes,Szentes,956243,2022-04-03,4.663998e+13,Horváth telep,2,Szentes,6600.0,Hungary,POINT (20.27563 46.63999)
3954624,1610621,1409778,1548953,Horváth telep,9 A,1213,Szentes,Szentes,956243,2022-04-03,4.663910e+13,Horváth telep,9,Szentes,6600.0,Hungary,POINT (20.27578 46.63916)
3954625,1610621,1413865,1552982,Nádasdy utca,12 A,1213,Szentes,Szentes,956243,2022-04-03,4.663514e+13,Nádasdy utca,12,Szentes,6600.0,Hungary,POINT (20.27404 46.63522)
3954626,1610621,1413865,1552982,Nádasdy utca,19 A,1213,Szentes,Szentes,956243,2022-04-03,4.663474e+13,Nádasdy utca,19,Szentes,6600.0,Hungary,POINT (20.27455 46.63485)
3954627,1610621,1413865,1552982,Nádasdy utca,19 A,1213,Szentes,Szentes,956243,2022-04-03,4.663484e+13,Nádasdy utca,19,Szentes,6600.0,Hungary,POINT (20.27455 46.63485)

In [33]:
(all_matched
    .query('date == "2022-04-03"')
    .drop(columns=['telepulesnev', 'kozteruletid', 'kozteruletnevid', 'telepulesid', 'telepulesnev_hu',
                   'telepulesnev', 'gid', 'utca', 'cim', 'orszag', 'eventfromid', 'iszam', 'date'])
    .rename(columns={'utca_gdf':'utca', 'cim_gdf':'hazszam'})
    .drop_duplicates()
    .to_file('../../adatok/working/osszekapcsolt_pontok_es_cimek.gpkg', layer='network_polygons', driver='GPKG')
)

In [34]:
gdfk = (all_matched
    .query('date == "2022-04-03"')
    .drop(columns=['telepulesnev', 'kozteruletid', 'kozteruletnevid', 'telepulesid', 'telepulesnev_hu',
                   'telepulesnev', 'gid', 'utca', 'cim', 'orszag', 'eventfromid', 'iszam', 'date'])
    .rename(columns={'utca_gdf':'utca', 'cim_gdf':'hazszam'})
    .drop_duplicates()
)

In [43]:
gdfk.query('telepules == "Szigetszentmiklós"').groupby('szavazokorid').count().shape

(30, 4)