In [1]:
import pandas as pd
import geopandas as gpd

from adat_strukturalas import *

In [2]:
gdf = gm_feldolgozas('../../adatok/fix/orszagos_teljes_ms.jsonl')

3686130 cím beolvasva
2190757 használható cím átadva ez a címek 59.43%-a
Google maps lekérdezés adatok standardizálva

In [3]:
gdf

,gid,utca,cim,telepules,iszam,orszag,geometry
0,47289911900891,Csalitos utca,6,Tököl,2316,Hungary,POINT (19.00889 47.28993)
1,47290591901043,Diana sétány,55,Tököl,2316,Hungary,POINT (19.01053 47.29057)
2,47289711900922,Diana sétány,71,Tököl,2316,Hungary,POINT (19.00921 47.28975)
3,47290281900996,Diana sétány,61,Tököl,2316,Hungary,POINT (19.00999 47.29026)
4,47283961900063,Diana sétány,147,Tököl,2316,Hungary,POINT (19.00071 47.28387)
...,...,...,...,...,...,...,...
2190752,46764301734911,Mogyorós utca,33,Balatongyörök,8313,Hungary,POINT (17.34902 46.76429)
2190753,46481191975105,Fő utca,181,Kiskunmajsa,6120,Hungary,POINT (19.75118 46.48119)
2190754,47452611956703,Bartók Béla utca,7,Tápiószecső,2251,Hungary,POINT (19.56709 47.4526)
2190755,47683021876780,Kálvária utca,52,Leányvár,2518,Hungary,POINT (18.76781 47.68296)
2190756,46171522060793,Petőfi Sándor utca,7,Magyarcsanád,6932,Hungary,POINT (20.60795 46.17151)

In [4]:
gdf = gdf.drop(columns=['gid'])

In [5]:
gdf.index.name = 'gid'
gdf = gdf.reset_index()

In [6]:
gdf

,gid,utca,cim,telepules,iszam,orszag,geometry
0,0,Csalitos utca,6,Tököl,2316,Hungary,POINT (19.00889 47.28993)
1,1,Diana sétány,55,Tököl,2316,Hungary,POINT (19.01053 47.29057)
2,2,Diana sétány,71,Tököl,2316,Hungary,POINT (19.00921 47.28975)
3,3,Diana sétány,61,Tököl,2316,Hungary,POINT (19.00999 47.29026)
4,4,Diana sétány,147,Tököl,2316,Hungary,POINT (19.00071 47.28387)
...,...,...,...,...,...,...,...
2190742,2190752,Mogyorós utca,33,Balatongyörök,8313,Hungary,POINT (17.34902 46.76429)
2190743,2190753,Fő utca,181,Kiskunmajsa,6120,Hungary,POINT (19.75118 46.48119)
2190744,2190754,Bartók Béla utca,7,Tápiószecső,2251,Hungary,POINT (19.56709 47.4526)
2190745,2190755,Kálvária utca,52,Leányvár,2518,Hungary,POINT (18.76781 47.68296)
2190746,2190756,Petőfi Sándor utca,7,Magyarcsanád,6932,Hungary,POINT (20.60795 46.17151)

In [9]:
gdf.to_csv('../../adatok/teljes_ms_lekerdezes_tisztott.csv', index=False, encoding='utf-8')

In [7]:
gdf.to_parquet('../../adatok/fix/teljes_ms_lekerdezes_tisztott.parquet')